// FIBONACCI WORD — Natural Period-0 Threshold
// Generated by: S_n = S_{n-1} + S_{n-2}
// Natural na binary na walang period

#include <iostream>
#include <string>
#include <cmath>

int main() {
    std::cout << "========================================\n";
    std::cout << "  FIBONACCI WORD\n";
    std::cout << "  Natural Period-0 Threshold\n";
    std::cout << "========================================\n\n";

    // Generate Fibonacci word
    std::string s0 = "0";
    std::string s1 = "01";
    
    std::cout << "GENERATION:\n";
    std::cout << "===========\n\n";
    std::cout << "  S_0 = " << s0 << "\n";
    std::cout << "  S_1 = " << s1 << "\n";
    
    std::string current = s1;
    for (int i = 2; i <= 8; i++) {
        current = s1 + s0;  // S_n = S_{n-1} + S_{n-2}
        s0 = s1;
        s1 = current;
        std::cout << "  S_" << i << " = " << current << "\n";
    }

    std::cout << "\nOBSERVATION:\n";
    std::cout << "============\n\n";
    std::cout << "  Ang Fibonacci word ay walang period.\n";
    std::cout << "  Ito ay natural na binary sequence.\n";
    std::cout << "  Ang bawat position ay 0 o 1.\n\n";

    // Beatty connection
    std::cout << "BEATTY CONNECTION:\n";
    std::cout << "=================\n\n";
    const double PHI = 1.6180339887498948482;
    const double PHI_SQ = PHI * PHI;

    std::cout << "  Position n at Beatty membership:\n";
    for (int n = 1; n <= 30; n++) {
        int b_phi = (int)std::floor(n * PHI);
        int b_phi_sq = (int)std::floor(n * PHI_SQ);
        
        // Check kung n ay nasa Beatty sequence
        bool in_phi = false;
        for (int k = 1; k <= 20; k++) {
            if ((int)std::floor(k * PHI) == n) in_phi = true;
            if ((int)std::floor(k * PHI_SQ) == n) in_phi = false;
        }
        
        std::cout << "  " << n << " → " << (in_phi ? "1" : "0") << "\n";
    }

    return 0;
}
