# ΦΩ0 — Pre-Computed Expected Values Generator v2
# Computes 2^n mod modulus for n = 0 to 1,000,000
# Output: ALL values hardcoded, compact format

modulus = 1073643521
total_steps = 1000000
entries_per_line = 10

print("// ΦΩ0 — PRE-COMPUTED EXPECTED VALUES v2")
print(f"// 2^n mod {modulus} for n = 0 to {total_steps}")
print("// Auto-generated by Python — DO NOT EDIT")
print()
print("#ifndef PHI_PRECOMPUTED_VALUES_H")
print("#define PHI_PRECOMPUTED_VALUES_H")
print()
print("#include <cstdint>")
print()
print(f"// All {total_steps + 1} entries, {entries_per_line} per line")
print(f"const int64_t PRECOMPUTED_VALUES[{total_steps + 1}] = {{")

val = 1
for n in range(total_steps + 1):
    if n % entries_per_line == 0:
        if n > 0:
            print()  # new line
        print("   ", end="")
    print(f" {val}LL,", end="")
    if n < total_steps:
        val = (val * 2) % modulus

print()  # final newline
print("};")
print()
print(f"// Total entries: {total_steps + 1}")
print(f"// Modulus: {modulus}")
print()
print("#endif // PHI_PRECOMPUTED_VALUES_H")
